#!/bin/bash
myvar=`cat ~/bin/rawdata/hhc`

echo $myvar
## borrar archivos .asoundrc y reemplaza por los existentes en skel
## cabe destacar, que no detecta la configuracion actual. así que siempre es
## recomendado correr el script un par de veces para reemplazar la config
## por defecto
if [[ $myvar -eq 1 ]]; ## pasar a headphones
then
	rm ~/.asoundrc
	rm ~/.asoundrc.asoundconf
	cp ~/bin/skel/hdmi ~/.asoundrc
	sudo alsactl restore
	echo 2 > ~/bin/rawdata/hhc
	clear
	echo "HDMI"
	exit
fi
if [[ $myvar -eq 2 ]] ;
	then
		rm ~/.asoundrc
		cp ~/bin/skel/headphones1 ~/.asoundrc
		cp ~/bin/skel/headphones2 ~/.asoundrc.asoundconf
		sudo alsactl restore
		echo 1 > ~/bin/rawdata/hhc
		clear
		echo "HEADPHONES"
		exit
fi

exit
